---
title: "Analysis"
author: "Ashish"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: paper
---

Preproc
===
```{r}
rm(list=ls())
library(nflfastR)
library(nflreadr)
library(tidyverse)
library(tidylog)
```


```{r}

df_player_stats = load_player_stats(2019:2023)

df_defense = load_player_stats(2023, stat_type="defense")

df_schedules = load_schedules(2023)

df_pbp = load_pbp(2023)
df_pbp$fumble_forced %>% table(useNA="always")
```

Calculate DEF fpts
===
```{r}
df_pbp %>% 
  group_by(game_id, home_team, away_team, week, season_type) %>% 
  summarize(
    
  )
```



```{r}
d <- df_player_stats %>% 
  filter(position == "WR") %>% 
  select(player_id, player_name, week, position, season, targets, receptions, fantasy_points) %>% 
  group_by(player_id, player_name, season) %>%
  summarize(
    receptions = sum(receptions, na.rm=TRUE),
    targets = sum(targets, na.rm=TRUE),
    fantasy_points = sum(fantasy_points, na.rm=TRUE)
  ) %>% 
  ungroup %>% 
  pivot_wider(names_from = season, values_from = c(targets, receptions, fantasy_points))
  

d %>% 
  lm(fantasy_points_2023 ~ targets_2022, data = .) %>%
  summary()
d %>% 
  lm(fantasy_points_2023 ~ fantasy_points_2022, data = .) %>%
  summary()
d %>% 
  lm(fantasy_points_2022 ~ targets_2021, data = .) %>%
  summary()
d %>%
  lm(fantasy_points_2022 ~ receptions_2021, data = .) %>%
  summary()
d %>%
  lm(fantasy_points_2022 ~ receptions_2021 + targets_2021, data = .) %>%
  summary()
d %>%
  lm(fantasy_points_2021 ~ receptions_2021 + targets_2021, data = .) %>%
  summary()

```





Session Info
===
```{r}
sessioninfo::session_info()
```

