---
title: "Analysis"
author: "Ashish"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: paper
---

Preproc
===
```{r}
rm(list=ls())
library(ffanalytics)
library(yaml)
library(tidyverse)
library(tidylog)
```

```{r}
config <- read_yaml("config.yaml")
```

```{r}
name_format <- function(name){
  name <- tolower(name)
  name <- str_replace_all(name, " ", "_")
  name
}
```


Read in sleeper
```{r}
ALL_PLAYERS_CSV <- config$files$sleeper$all_players_csv

cols <- c("full_name", "team", "position", "positional_rank", "adp", "adp_date", "first_name","last_name", "status",  "injury_start_date", "injury_notes","sleeper_id", "age", "practice_participation", "depth_chart_order", "fantasy_positions","number", "team_abbr",   "rank_int")

df_sleeper_players_raw <- read_csv(ALL_PLAYERS_CSV)

df_sleeper_players <- df_sleeper_players_raw %>% 
  select(one_of(cols)) %>% 
  mutate(full_name = name_format(full_name))
```

Read in fantasydata
```{r}
FANTASYDATA_CSV <- config$files$fantasydata$fpts_all_ssns

df_fantasydata_raw <- read_csv(FANTASYDATA_CSV)

df_fantasydata <- df_fantasydata_raw %>% 
  mutate(full_name = name_format(name)) %>% 
  select(-name)

df_fd_reg <- df_fantasydata %>% 
  filter(ssn_type == "REG")

df_fd_reg2023 <- df_fd_reg %>% 
  filter(year == "2023")


df_fd_fpts_3yrs <- df_fantasydata %>% 
  filter(year %in% c("2021", "2022", "2023")) %>% 
  select(full_name, season, fpts, fpts_per_game) %>% 
  pivot_wider(names_from = season, values_from = c(fpts, fpts_per_game))
```

Scraping with ffanalytics
===
```{r}
ffa_2024_scrape <- scrape_data(
  src = c("CBS", "ESPN", "FantasyPros", "FantasySharks", "FFToday", "FleaFlicker",
    "NumberFire", "FantasyFootballNerd", "NFL", "RTSports", "Walterfootball"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST"),
  season = 2024,
  week = 0
)
ffa_2024_proj <- projections_table(ffa_2024_scrape) %>%
  add_ecr() %>% 
  # add_risk() %>%  # could not find function "add_risk"
  add_adp() %>% 
  add_aav() %>% 
  add_player_info()

```



Combining sleeper and fantasydata
===
```{r}
d <- df_sleeper_players %>% 
  filter(!full_name %in% df_fd_fpts_3yrs$full_name)
view(d)
df_sleeper_players$full_name %in% df_fd_reg2023$full_name
```


Explore history
===
```{r}

```



Positional scarcity
===
```{r}


```



Historical player data
===




Historical manager analysis
===


Estimate variance
===

```{r}

```

```{r}
library(nflreadr)


# Load the necessary libraries
library(tidyverse)


df_sleeper <- read_csv("data/sleeper/all_players.csv")
df_qb_proj <- read_csv("data/projections/QB_projections.csv") 
df_rb_proj <- read_csv("data/projections/RB_projections.csv")
df_wr_proj <- read_csv("data/projections/WR_projections.csv")
df_te_proj <- read_csv("data/projections/TE_projections.csv")
df_k_proj <- read_csv("data/projections/K_projections.csv")
df_def_proj <- read_csv("data/projections/DEF_projections.csv")

df_proj <- df_qb_proj %>% 
  select(sleeper_id, full_name, team, position, source, fpts) %>%
  mutate(sleeper_id = as.character(sleeper_id)) %>%
  bind_rows(
    df_rb_proj %>% 
      select(sleeper_id, full_name, team, position, source, fpts) %>% 
      mutate(sleeper_id = as.character(sleeper_id))
  ) %>% 
  bind_rows(
    df_wr_proj %>% 
      select(sleeper_id, full_name, team, position, source, fpts) %>% 
      mutate(sleeper_id = as.character(sleeper_id))
  ) %>% 
  bind_rows(
    df_te_proj %>% 
      select(sleeper_id, full_name, team, position, source, fpts) %>% 
      mutate(sleeper_id = as.character(sleeper_id))
  ) %>%
  bind_rows(
    df_k_proj %>% 
      select(sleeper_id, full_name, team, position, source, fpts) %>% 
      mutate(sleeper_id = as.character(sleeper_id))
  ) %>%
  bind_rows(
    df_def_proj %>% 
      select(sleeper_id, full_name, team, position, source, fpts) %>% 
      mutate(sleeper_id = as.character(sleeper_id))
  ) %>% 
  group_by(sleeper_id, full_name, team, position) %>% 
  summarize(
    n_proj = n(),
    mean_proj = mean(fpts, na.rm=T),
    sd_proj = sd(fpts, na.rm=T),
    min_proj = min(fpts, na.rm=T),
    max_proj = max(fpts, na.rm=T)
  ) %>% 
  ungroup 


df_hist_raw = load_player_stats(seasons = 2021:2023) %>% 
  filter(position %in% c("QB", "RB", "WR", "TE")) %>% 
  mutate(halfppr = fantasy_points_ppr - .5*receptions) 
df_hist = df_hist_raw %>% 
  group_by(player_display_name, position, season) %>% 
  summarize(
    n_games = n(),
    mean_fp = mean(halfppr, na.rm=T),
    sd_fp = sd(halfppr, na.rm=T),
    var_fp = var(halfppr, na.rm=T)
  ) %>% 
  summarize(
    n_ssns = n(),
    n_games = sum(n_games, na.rm=T),
    mean_ssn_fp = mean(mean_fp, na.rm=T),
    mean_sd_fp = mean(sd_fp, na.rm=T),
    mean_var_fp = mean(var_fp, na.rm=T)
  ) %>% 
  ungroup %>% 
  select(-position) %>% 
  rename(hist_name = player_display_name)

# df_nflverse_stats %>% 
#   write_csv("data/nflverse/mean_var_weekly_fp.csv")

library(stringdist)

df_full <- df_proj %>% 
  mutate(row_num = map_dbl(full_name, ~{
    amatch(., df_hist$hist_name, method="lv", maxDist = 3)
  })) %>% 
  left_join(df_hist %>% 
              mutate(row_num = row_number()), 
            by="row_num") 
  

  # select(player_display_name, full_name, season, week, position, fantasy_points) %>% 
  # filter(!is.na(full_name)) %>% 
  # group_by(full_name, season) %>% 
  # summarize(
  #   mean_fp = mean(fantasy_points),
  #   sd_fp = sd(fantasy_points)
  # ) %>% 
  # ungroup %>% 
  # pivot_wider(names_from = season, values_from = c(mean_fp, sd_fp))

```


```{r}
d <- load_pfr_advstats(
  seasons = 2021:2023,
  stat_type = "def",
  summary_level = "week"
)
```


```{r}

f <- function(){
  a <- 1
  b <- 1
  for(i in 1:1000){
    
    p = rbeta(1, a, b)
    
    x = rbinom(1, 1, p)
    
    if (x == 1){
      a = a + 1
    } else {
      b = b + 1
    }
  }
  return (a/(a+b))
}

sims <- replicate(1000, f())
```

```{r}
mean(sims)
```


```{r}
qb <- read_csv("data/nflverse/qb_mean_var.csv")
```



